# Generated by Django 2.0.2 on 2018-04-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('weight', models.PositiveSmallIntegerField(default=1, verbose_name='Вес')),
                ('is_start_package', models.BooleanField(default=False, verbose_name='Начальный тариф')),
                ('max_webinars', models.SmallIntegerField(default=0, verbose_name='Максимальное количество вебинаров')),
                ('max_lending_to_webinar', models.SmallIntegerField(default=0, verbose_name='Максимальное количество лендингов у вебинара')),
                ('can_create_premium_template', models.BooleanField(default=False, verbose_name='Может создавать премиум шаблоны')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ('weight',),
            },
        ),
    ]
