# Generated by Django 2.0.2 on 2018-04-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0001_initial'),
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinar.Webinar', verbose_name='Вебинар'),
        ),
    ]
