# Generated by Django 2.0.2 on 2018-04-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_landing_webinar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landing',
            name='landing_code',
        ),
    ]
