# Generated by Django 2.0.2 on 2018-04-03 09:18

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='ISO Code')),
                ('course', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс по отношению к главной валюте')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
    ]
