# Generated by Django 2.0.2 on 2018-04-14 15:30

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to=images.models.set_image_name, verbose_name='Изображение'),
        ),
    ]
