# Generated by Django 2.0.2 on 2018-04-26 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20180414_1127'),
        ('images', '0002_auto_20180414_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('langing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Landing')),
                ('userimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.UserImage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userimage',
            name='landing',
            field=models.ManyToManyField(through='images.LandingImage', to='landing.Landing', verbose_name='Лендинги'),
        ),
    ]
