# Generated by Django 2.0.2 on 2018-04-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20180426_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingimage',
            name='email_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
