# Generated by Django 2.0.2 on 2018-04-03 09:18

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import mlm_builder.utils
import sorl.thumbnail.fields
import webinar.models
import webinar.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('video', models.URLField(validators=[webinar.validators.youtube_validator], verbose_name='Видео')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=mlm_builder.utils.set_filename, verbose_name='Изображение')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор')),
                ('active_start_date', models.DateTimeField(verbose_name='Дата старта показа')),
                ('active_end_date', models.DateTimeField(verbose_name='Дата прекращения показа')),
                ('is_moderate', models.BooleanField(default=False, verbose_name='Одобренно модератором')),
                ('owner', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Вебинар',
                'verbose_name_plural': 'Вебинары',
            },
        ),
        migrations.CreateModel(
            name='WebinarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('code', models.CharField(default=webinar.models.get_unique_code, max_length=8, unique=True, verbose_name='Код')),
                ('is_visit', models.BooleanField(default=False, verbose_name='Посещал вебинар')),
                ('landing', models.ForeignKey(on_delete=None, to='landing.Landing', verbose_name='Ленгинг')),
                ('owner', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('webinar', models.ForeignKey(on_delete=None, to='webinar.Webinar', verbose_name='Вебинар')),
            ],
            options={
                'verbose_name': 'Пользователи вебинара',
                'verbose_name_plural': 'Пользователи вебинара',
            },
        ),
    ]
